<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNXomkYi\AdminKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNXomkYi/AdminKernelProdContainer.php') {
    touch(__DIR__.'/ContainerNXomkYi.legacy');

    return;
}

if (!\class_exists(AdminKernelProdContainer::class, false)) {
    \class_alias(\ContainerNXomkYi\AdminKernelProdContainer::class, AdminKernelProdContainer::class, false);
}

return new \ContainerNXomkYi\AdminKernelProdContainer([
    'container.build_hash' => 'NXomkYi',
    'container.build_id' => 'd8b51e2c',
    'container.build_time' => 1776593025,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNXomkYi');
