<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGoJbxde\AdminKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGoJbxde/AdminKernelProdContainer.php') {
    touch(__DIR__.'/ContainerGoJbxde.legacy');

    return;
}

if (!\class_exists(AdminKernelProdContainer::class, false)) {
    \class_alias(\ContainerGoJbxde\AdminKernelProdContainer::class, AdminKernelProdContainer::class, false);
}

return new \ContainerGoJbxde\AdminKernelProdContainer([
    'container.build_hash' => 'GoJbxde',
    'container.build_id' => '66a86f56',
    'container.build_time' => 1776868922,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGoJbxde');
