<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRPT7KOu\AdminKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRPT7KOu/AdminKernelProdContainer.php') {
    touch(__DIR__.'/ContainerRPT7KOu.legacy');

    return;
}

if (!\class_exists(AdminKernelProdContainer::class, false)) {
    \class_alias(\ContainerRPT7KOu\AdminKernelProdContainer::class, AdminKernelProdContainer::class, false);
}

return new \ContainerRPT7KOu\AdminKernelProdContainer([
    'container.build_hash' => 'RPT7KOu',
    'container.build_id' => 'c761f85e',
    'container.build_time' => 1776781622,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRPT7KOu');
